version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./wwwroot:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
            - src
    php:
        build: docker
        restart: always
        env_file: .env
        volumes:
            - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./wwwroot:/var/www/html
            #- ./wwwroot:/src


    composer:
        image: composer
        volumes:
            - ./wwwroot:/app
        command: install
    db:
        image: postgres:10.6
        restart: always
        depends_on:
            - src
        env_file: .env
        ports:
            - 15432:5432
        volumes:
            - ./docker/conf/postgres/initdb.d/:/docker-entrypoint-initdb.d/
            - ./postgresql-data/:/var/lib/postgresql/data/
    src:
        build: project
        image: ws_src
        env_file: .env
        volumes:
            - ${PWD}/docker/conf/postgres/initdb.d/init.sql:/initdb.sql
            - ./wwwroot:/src
